apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
spec:
  selector:
    matchLabels:
      app: vpromc
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
      - name: memcached
        image: memcached:1.5.20
        ports:
        - containerPort: 11211
