apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels: 
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1 
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
       - name: vprofiledb
         image: vprofile/vprofiledb
         ports:
          - containerPort: 3306

